version: '3.8'

services:

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=admin
  project1:
    build:
      context: ./admin-panel-crud
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - ./admin-panel-crud/.env
    environment:
      TZ: "Asia/Oral"
  project2:
    build:
      context: ./admin-panel-eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      TZ: "Asia/Oral"
  project3:
    build:
      context: ./admin-panel-gateway
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    env_file:
      - ./admin-panel-gateway/.env
    environment:
      TZ: "Asia/Oral"
  project4:
    build:
      context: ./admin-panel-security
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./admin-panel-security/.env
    environment:
      TZ: "Asia/Oral"
  websocket:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      TZ: "Asia/Oral"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
