spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Используйте update после первого запуска для сохранения данных между перезапусками
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
  application:
    name: ${APPLICATION_NAME}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

server:
  port: 8084
  servlet:
    context-path: ${SERVER_CONTEXT_PATH}

redis:
  host: localhost
  port: 6379
feign:
  url: ${FEIGN}
