spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      open-in-view: false
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
  application:
    name: ${APPLICATION_NAME}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

server:
  port: 8084
redis:
  host: localhost
  port: 6379
  password: 1234
feign:
  url: ${FEIGN}
